server:
  port: 80


spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2c00f1e35f481ded17352b09d4ae8069
            client-secret: VRHj4gDL57l2wHwC9JAPsyeyucwZMb1i
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      enabled: true
      location: C:\Users\user\Desktop\data
      max-request-size: 30MB
      max-file-size: 10MB

  datasource:
    url: jdbc:mariadb://localhost:3306/Movie
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #hibernate query ??? ??
        show_sql: true #hibernate query? ??? ??

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

com:
  example:
    upload:
      path: C:\Users\user\Desktop\data
